sonar.projectKey=project3
sonar.projectName=project3
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_c69fcd9d401c45099a88e05298af694c8d01d6c0
